FROM node:lts-alpine

RUN mkdir /mcp
WORKDIR /mcp

COPY src src
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json tsconfig.json

RUN npm install
RUN npm run build

ENV PORT=3001

EXPOSE $PORT

CMD ["node","dist/server.js","--sse","--serve"]